name: Mayhem
on:
  push:
  pull_request:
  workflow_dispatch:
      
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  PARSE_PARQUET: parse_parquet.mayhemfile

jobs:
  build:
    name: '${{ matrix.os }} shared=${{ matrix.shared }} ${{ matrix.build_type }}'
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      matrix:
        os: [ubuntu-latest]
        shared: [false]
        build_type: [Release]
        include:
          - os: ubuntu-latest
            triplet: x64-linux

    steps:
      - uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Rust Build Cache
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - uses: Swatinem/rust-cache@v1

      - uses: actions-rs/cargo@v1
      - run: |
          sudo swapon -s
          free -m
          df -h
          sudo fallocate -l 8G /swapfile
          ls -lh /swapfile
          sudo chmod 600 /swapfile
          ls -lh /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          sudo swapon -s
          free -m
          cargo install cargo-fuzz
          cd polars/fuzz
          cargo fuzz build

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Start analysis for PARSE_PARQUET
        uses: ForAllSecure/mcode-action@v1
        with:
          mayhem-token: ${{ secrets.MAYHEM_TOKEN }}
          args: --image ${{ steps.meta.outputs.tags }} --file ${{ env.PARSE_PARQUET }} --duration 1200
          sarif-output: sarif

